// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

// Interface for Groth16 Verifier (which would be generated by SnarkJS)
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[1] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title ZkKycSBT
 * @dev Soulbound Token representing a Zero-Knowledge KYC verification.
 */
contract ZkKycSBT is ERC721, Ownable {
    uint256 private _nextTokenId;
    IVerifier public verifier;

    // Mapping from wallet address to boolean indicating verification
    mapping(address => bool) private _verifiedUsers;

    // Custom errors
    error TokenIsSoulbound();
    error InvalidZeroKnowledgeProof();
    error AlreadyVerified();

    // Event
    event Verified(address indexed user, uint256 tokenId, uint256 timestamp);

    constructor(address _verifierAddress) ERC721("zk-KYC Identity", "zkKYC") Ownable(msg.sender) {
        verifier = IVerifier(_verifierAddress);
        _nextTokenId = 1;
    }

    /**
     * @dev Mint a new Soulbound Token upon successful ZK Proof verification.
     * @param _pA Proof A from Groth16
     * @param _pB Proof B from Groth16
     * @param _pC Proof C from Groth16
     * @param _pubSignals Public signals from Groth16 (e.g. proof of valid passport nullifier)
     */
    function mint(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[1] calldata _pubSignals
    ) external {
        if (_verifiedUsers[msg.sender]) {
            revert AlreadyVerified();
        }

        // Verify the ZK proof
        bool isValidProof = verifier.verifyProof(_pA, _pB, _pC, _pubSignals);
        if (!isValidProof) {
            revert InvalidZeroKnowledgeProof();
        }

        // If proof is valid, set verification status and mint SBT
        _verifiedUsers[msg.sender] = true;
        uint256 tokenId = _nextTokenId++;
        
        _safeMint(msg.sender, tokenId);

        emit Verified(msg.sender, tokenId, block.timestamp);
    }

    /**
     * @dev Update verifier contract address
     */
    function setVerifier(address _newVerifier) external onlyOwner {
        verifier = IVerifier(_newVerifier);
    }

    /**
     * @dev Check if a given address is completely verified. 
     *      Useful for external DeFi apps to call.
     */
    function isVerified(address user) external view returns (bool) {
        return _verifiedUsers[user] && balanceOf(user) > 0;
    }

    /**
     * @dev Block all transfers by overriding the internal _update hook.
     *      Allows minting (from == 0) and burning (to == 0).
     */
    function _update(address to, uint256 tokenId, address auth) internal override returns (address) {
        address from = _ownerOf(tokenId);
        if (from != address(0) && to != address(0)) {
            revert TokenIsSoulbound();
        }
        return super._update(to, tokenId, auth);
    }

    /**
     * @dev Simple metadata URI for the token.
     */
    function _baseURI() internal pure override returns (string memory) {
        return "https://api.zk-kyc.app/metadata/";
    }
}
