import { ethers } from "hardhat";

async function main() {
  console.log("Starting deployment of zk-KYC Soulbound Token...");

  // In a real scenario, you'd deploy the Verifier.sol contract first
  // (generated by SnarkJS) and pass its address to the SBT contract.
  
  // For demonstration, we'll assume a mock verifier or a previously deployed one.
  const MOCK_VERIFIER_ADDRESS = "0x0000000000000000000000000000000000000000";

  // Deploying the Soulbound Token contract
  const ZkKycSBT = await ethers.getContractFactory("ZkKycSBT");
  const zkKycSbt = await ZkKycSBT.deploy(MOCK_VERIFIER_ADDRESS);

  await zkKycSbt.waitForDeployment();

  const contractAddress = await zkKycSbt.getAddress();

  console.log("----------------------------------------------------");
  console.log(`zk-KYC SBT deployed to: ${contractAddress}`);
  console.log("----------------------------------------------------");
  
  console.log("Deployment complete. Copy the address to your frontend config.");
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
